# Generated by Django 3.2 on 2021-04-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('LONGITUDE', models.FloatField(help_text='Longitude of the sight')),
                ('LATITUDE', models.FloatField(help_text='Latitude of the sight')),
                ('SQUIRREL_ID', models.CharField(default='123ABC', help_text='Unique Sighting ID of the squirrel', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('SHIFT', models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Whether sighting happens in the morning or late afternoon', max_length=100)),
                ('DATE', models.DateField(help_text='Date of the sighting')),
                ('AGE', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age Category of the Squirrel', max_length=50)),
                ('FUR_COLOR', models.CharField(blank=True, choices=[('Grey', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Fur Color of the Squirrel', max_length=50)),
                ('LOCATION', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location where squirrel is found', max_length=200)),
                ('SPECIFIC_LOCATION', models.CharField(blank=True, help_text='Any additional notes regarding location', max_length=200)),
                ('RUNNING', models.BooleanField(default=False, help_text='Running')),
                ('CHASING', models.BooleanField(default=False, help_text='Chasing')),
                ('CLIMBING', models.BooleanField(default=False, help_text='Climbing')),
                ('EATING', models.BooleanField(default=False, help_text='Eating')),
                ('FORAGING', models.BooleanField(default=False, help_text='Foraging')),
                ('OTHER_ACTIVITIES', models.CharField(blank=True, help_text='Other Activities Noted', max_length=300)),
                ('KUKS', models.BooleanField(default=False, help_text='Kuks')),
                ('QUAAS', models.BooleanField(default=False, help_text='Quaas')),
                ('MOANS', models.BooleanField(default=False, help_text='Moans')),
                ('TAIL_FLAGS', models.BooleanField(default=False, help_text='Tail Flags')),
                ('TAIL_TWITCH', models.BooleanField(default=False, help_text='Tail Twitches')),
                ('APPROACHES', models.BooleanField(default=False, help_text='Approaches humans')),
                ('RUNS_FROM', models.BooleanField(default=False, help_text='Runs away from humans')),
            ],
        ),
    ]
